{{- include "helm-library.configmap" (list . "heatmap.configmap") -}}
{{- define "heatmap.configmap" -}}
data:
  PORT: {{ .Values.container.port | quote }}
  NODE_ENV: {{ .Values.configMap.environment | quote }}
{{- end -}}
